layers:
  QWERTY:
  - TAB
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - BSPC
  - LCTRL
  - A
  - S
  - D
  - F
  - G
  - H
  - J
  - K
  - L
  - \
  - '='
  - LSHFT
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - ','
  - .
  - /
  - ESC
  - '&alt_td_nl'
  - LCMD
  - SPACE
  - RET
  - NUMBER / ÅÄÖ
  - {t: ESC, h: MEDIA}
  NUMBER / ÅÄÖ:
  - +
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - BSPC
  - LCTL
  - ''
  - '`'
  - Sft+ `
  - '-'
  - ']'
  - LEFT
  - DOWN
  - UP
  - RIGHT
  - ''
  - ''
  - LSFT
  - ''
  - ''
  - ''
  - ''
  - '&macro_spotlight'
  - ;
  - ''''
  - '['
  - ''
  - ''
  - ''
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - SPACE
  - RET
  - {type: held}
  - ESC
  MEDIA:
  - {t: ▽, type: trans}
  - {t: BT, h: '0'}
  - {t: BT, h: '1'}
  - {t: BT, h: '2'}
  - {t: BT, h: '3'}
  - {t: BT, h: '4'}
  - PREVIOUS
  - PLAY PAUSE
  - NEXT
  - VOLUME DOWN
  - VOLUME UP
  - MUTE
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - BT CLR
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - RGB TOG
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  EXTRA 1:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  EXTRA 2:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  EXTRA 3:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  EXTRA 4:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  EXTRA 5:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  EXTRA 6:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
